## Inverse of a matrix

In [2]:
import numpy as np 

# concept of inversion of a matrix
x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 

print (x) 
print (y) 
print (np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


## 2.4 Compute the folowing matrix products

In [6]:
# lets multiply an array
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

y = np.array([[1, 1, 0],
              [0, 1, 1],
              [1, 0, 1]])


print('Matrix Dot Product')
print(np.dot(x, y))

Matrix Dot Product
[[ 4  3  5]
 [10  9 11]
 [16 15 17]]


In [5]:
# lets multiply an array
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

y = np.array([[1, 1, 0],
              [0, 1, 1],
              [1, 0, 1]])


print('Matrix Dot Product')
print(np.dot(y, x))

Matrix Dot Product
[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]


In [10]:
x = np.array([[1, 2, 1, 2],
              [4, 1, -1, -4]])

y = np.array([[0, 3],
              [1, -1],
              [2, 1],
              [5, 2]])


print(x.dot(y))
print(x @ y)


[[ 14   6]
 [-21   2]]
[[ 14   6]
 [-21   2]]


## 2.3 Find the set of allsolutions in x, Ax = b

In [22]:
A = np.array([[1, 1, -1, -1],
              [2, 5, -7, -5],
              [2, -1, 1, 3],
              [5, 2, -4, 2]])

b = np.array([[1],
              [-2],
              [4],
              [6]])

# Find x from Ax = b
x = np.invert(A).dot(b)
print(x)

[[  2]
 [ 57]
 [-35]
 [ -6]]


In [21]:
import scipy.linalg as la

x = la.solve(A,b)
print(x)

[[ 8.57828500e+14]
 [-3.43131400e+15]
 [-1.28674275e+15]
 [-1.28674275e+15]]


In [35]:
A = np.array([[1, -1, 0,  1],
              [1,  1, 0,  0],
              [2, -1, 0, -1],
              [-1, 2, 0, -1]])

b = np.array([[3],
              [6],
              [5],
              [-1]])

# Find x from Ax = b
A_inv = np.invert(A)
x = np.dot(A_inv, b)
print(x)

# using moore–penrose pseudo inverse
A_transp = np.transpose(A)
A_transp_dot_A_inv = np.invert(np.dot(A_transp, A))
x = np.dot( A_transp_dot_A_inv, A_transp)
print(x)

np.linalg.pinv(A)


[[ -9]
 [-22]
 [-14]
 [-23]]
[[-12  -5 -18  15]
 [ 12  -5  13 -20]
 [ -1  -2   0   0]
 [ -6   0   1   7]]


array([[ 0.18309859,  0.4084507 ,  0.1971831 , -0.01408451],
       [ 0.07042254,  0.46478873, -0.15492958,  0.22535211],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.38028169,  0.30985915, -0.43661972, -0.18309859]])

In [20]:
print(A_inv)

[[-2  0 -1 -2]
 [-2 -2 -1 -1]
 [-3  0 -1  0]
 [ 0 -3 -1  0]]


In [36]:
np.invert(A.T.dot(A)).dot(A.T).dot(b)

array([[-171],
       [  91],
       [ -15],
       [ -20]])

In [40]:
np.linalg.inv(A.T.dot(A))

LinAlgError: Singular matrix